# Generated by Django 4.2.5 on 2023-12-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("fax", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("members_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Envoy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="photos")),
                ("first_name", models.CharField(max_length=255)),
                (
                    "second_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                (
                    "inactive_cause",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("waiver_desc", models.TextField(blank=True, null=True)),
                ("district_num", models.IntegerField()),
                ("district_name", models.CharField(max_length=255)),
                ("voivodeship", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("birth_location", models.CharField(max_length=255)),
                ("profession", models.CharField(max_length=255)),
                ("education_level", models.CharField(max_length=255)),
                ("number_of_votes", models.IntegerField()),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envoys",
                        to="sejm_app.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sitting",
                    models.IntegerField(
                        blank=True, help_text="Number of the Sejm sitting", null=True
                    ),
                ),
                (
                    "sittingDay",
                    models.IntegerField(
                        blank=True,
                        help_text="Day number of the Sejm sitting",
                        null=True,
                    ),
                ),
                (
                    "votingNumber",
                    models.IntegerField(
                        blank=True, help_text="Voting number", null=True
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True, help_text="Date of the vote", null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Voting topic", max_length=255, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Voting description",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Short voting topic",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pdfLink",
                    models.URLField(
                        blank=True,
                        help_text="Link to the PDF document with voting details",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        help_text="Type of voting, one of ELECTRONIC, TRADITIONAL, ON_LIST",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VotingOption",
            fields=[
                (
                    "optionIndex",
                    models.IntegerField(
                        help_text="Index of the option on the list",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option",
                    models.CharField(
                        blank=True,
                        help_text="Name of the option",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of the option",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "votes",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of votes for this option",
                        null=True,
                    ),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        blank=True,
                        help_text="Voting this option belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sejm_app.voting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.CharField(blank=True, max_length=255, null=True)),
                ("listVotes", models.JSONField(blank=True, null=True)),
                ("mP", models.IntegerField(blank=True, null=True)),
                (
                    "MP",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sejm_app.envoy",
                    ),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="sejm_app.voting",
                    ),
                ),
            ],
        ),
    ]
