# Generated by Django 5.0 on 2024-02-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="from_not_envoy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
