# Generated by Django 5.0 on 2024-02-28 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0002_reply_from_not_envoy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote",
            field=models.SmallIntegerField(
                choices=[
                    (0, "No"),
                    (1, "Yes"),
                    (2, "ABSTAIN"),
                    (3, "ABSENT"),
                    (4, "VOTE_VALID"),
                ],
                help_text="Vote option",
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="id",
            field=models.IntegerField(
                help_text="Voting ID", primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="ClubVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.SmallIntegerField(
                        choices=[
                            (0, "No"),
                            (1, "Yes"),
                            (2, "ABSTAIN"),
                            (3, "ABSENT"),
                            (4, "VOTE_VALID"),
                        ],
                        help_text="Vote option",
                    ),
                ),
                (
                    "percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of club members who voted to this option",
                        null=True,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="sejm_app.club",
                    ),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_votes",
                        to="sejm_app.voting",
                    ),
                ),
            ],
        ),
    ]
