# Generated by Django 5.0 on 2023-12-22 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0002_alter_printmodel_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voting",
            old_name="pdfLink",
            new_name="pdf_link",
        ),
        migrations.RenameField(
            model_name="voting",
            old_name="sittingDay",
            new_name="sitting_day",
        ),
        migrations.RenameField(
            model_name="voting",
            old_name="votingNumber",
            new_name="voting_number",
        ),
    ]
