# Generated by Django 5.0 on 2023-12-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0003_rename_pdflink_voting_pdf_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("UE", models.CharField(max_length=2)),
                ("description", models.TextField()),
                ("document_type", models.CharField(max_length=255)),
                ("legislative_committee", models.BooleanField()),
                ("principle_of_subsidiarity", models.BooleanField()),
                ("process_start_date", models.DateField()),
                ("urgency_withdraw_date", models.DateField(blank=True, null=True)),
                ("rcl_num", models.CharField(max_length=20)),
                ("term", models.IntegerField()),
                ("title", models.TextField()),
                ("urgency_status", models.CharField(max_length=20)),
                (
                    "print_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sejm_app.printmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("stage_name", models.CharField(max_length=255)),
                ("sitting_num", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("decision", models.CharField(blank=True, max_length=255, null=True)),
                ("text_after_3", models.URLField(blank=True, null=True)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sejm_app.process",
                    ),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sejm_app.voting",
                    ),
                ),
            ],
        ),
    ]
