# Generated by Django 4.2.5 on 2023-12-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0003_remove_vote_listvotes_remove_vote_mp_alter_vote_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="voting",
            name="abstain",
            field=models.SmallIntegerField(
                blank=True, help_text="Abstain votes", null=True
            ),
        ),
        migrations.AddField(
            model_name="voting",
            name="no",
            field=models.SmallIntegerField(blank=True, help_text="No votes", null=True),
        ),
        migrations.AddField(
            model_name="voting",
            name="yes",
            field=models.SmallIntegerField(
                blank=True, help_text="Yes votes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="vote",
            field=models.SmallIntegerField(
                choices=[(1, "Yes"), (0, "No"), (2, "ABSTAIN"), (3, "ABSENT")],
                help_text="Vote option",
            ),
        ),
    ]
