# Generated by Django 5.0 on 2024-02-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0003_alter_vote_vote_alter_voting_id_clubvote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubvote",
            name="percentage",
        ),
        migrations.RemoveField(
            model_name="clubvote",
            name="vote",
        ),
        migrations.AddField(
            model_name="clubvote",
            name="abstain",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clubvote",
            name="no",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clubvote",
            name="yes",
            field=models.IntegerField(default=0),
        ),
    ]
