# Generated by Django 5.0 on 2023-12-22 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0004_process_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="change_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 22, 16, 59, 51, 274104, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
