# Generated by Django 5.0 on 2024-03-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0004_remove_clubvote_percentage_remove_clubvote_vote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="envoy",
            name="biography",
            field=models.TextField(
                blank=True,
                help_text="Biography of the envoy pulled from wikipedia",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="envoy",
            name="biography_source",
            field=models.URLField(
                blank=True,
                help_text="URL to the wikipedia page of the envoy",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clubvote",
            name="voting",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_votes",
                to="sejm_app.voting",
            ),
            preserve_default=False,
        ),
    ]
