# Generated by Django 5.0 on 2023-12-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0005_process_change_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="UE",
            field=models.BooleanField(
                blank=True, choices=[(True, "YES"), (False, "NO")], null=True
            ),
        ),
    ]
