# Generated by Django 5.0 on 2024-03-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0005_envoy_biography_envoy_biography_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="MPs",
            field=models.ManyToManyField(
                blank=True, related_name="processes", to="sejm_app.envoy"
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processes",
                to="sejm_app.club",
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="created_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("posłowie", "Envoys"),
                    ("klub", "Club"),
                    ("prezydium", "Presidium"),
                    ("obywatele", "Citizens"),
                    ("rząd", "Government"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
