# Generated by Django 4.2.5 on 2023-12-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0006_alter_vote_mp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scandal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("url1", models.URLField(blank=True, null=True)),
                ("url2", models.URLField(blank=True, null=True)),
                (
                    "clubs",
                    models.ManyToManyField(
                        blank=True, related_name="scandals", to="sejm_app.club"
                    ),
                ),
                (
                    "envoys",
                    models.ManyToManyField(
                        blank=True, related_name="scandals", to="sejm_app.envoy"
                    ),
                ),
            ],
        ),
    ]
