# Generated by Django 5.0 on 2024-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0006_process_mps_process_club_process_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="members_count",
            new_name="membersCount",
        ),
        migrations.AlterField(
            model_name="club",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="club_logos"),
        ),
    ]
