# Generated by Django 5.0 on 2024-03-22 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0007_rename_members_count_club_memberscount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="envoy",
            old_name="birth_date",
            new_name="birthDate",
        ),
        migrations.RenameField(
            model_name="envoy",
            old_name="birth_location",
            new_name="birthLocation",
        ),
        migrations.RenameField(
            model_name="envoy",
            old_name="district_name",
            new_name="districtName",
        ),
        migrations.RenameField(
            model_name="envoy",
            old_name="district_num",
            new_name="districtNum",
        ),
        migrations.RenameField(
            model_name="envoy",
            old_name="education_level",
            new_name="educationLevel",
        ),
        migrations.RenameField(
            model_name="envoy",
            old_name="first_name",
            new_name="firstName",
        ),
        migrations.RenameField(
            model_name="envoy",
            old_name="inactive_cause",
            new_name="inactiveCause",
        ),
        migrations.RenameField(
            model_name="envoy",
            old_name="last_name",
            new_name="lastName",
        ),
        migrations.RenameField(
            model_name="envoy",
            old_name="number_of_votes",
            new_name="numberOfVotes",
        ),
        migrations.RenameField(
            model_name="envoy",
            old_name="second_name",
            new_name="secondName",
        ),
        migrations.RenameField(
            model_name="envoy",
            old_name="waiver_desc",
            new_name="waiverDesc",
        ),
    ]
