# Generated by Django 5.0 on 2023-12-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0007_remove_process_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="id",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
