# Generated by Django 5.0 on 2024-03-22 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0008_rename_birth_date_envoy_birthdate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voting",
            old_name="pdf_link",
            new_name="pdfLink",
        ),
        migrations.RenameField(
            model_name="voting",
            old_name="sitting_day",
            new_name="sittingDay",
        ),
        migrations.RenameField(
            model_name="voting",
            old_name="voting_number",
            new_name="votingNumber",
        ),
    ]
