# Generated by Django 5.0 on 2023-12-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0008_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="scandal",
            name="entry_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
