# Generated by Django 5.0 on 2023-12-22 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0008_alter_process_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="process",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sejm_app.process",
            ),
        ),
    ]
