# Generated by Django 5.0 on 2024-01-17 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0009_alter_stage_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="process",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="sejm_app.process",
            ),
        ),
    ]
