# Generated by Django 5.0 on 2024-03-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0009_rename_pdf_link_voting_pdflink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voting",
            name="success",
            field=models.BooleanField(
                blank=True, help_text="Whether the voting was successful", null=True
            ),
        ),
    ]
