# Generated by Django 5.0 on 2024-03-22 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0010_voting_success"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printmodel",
            name="change_date",
        ),
        migrations.RemoveField(
            model_name="printmodel",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="printmodel",
            name="document_date",
        ),
        migrations.AddField(
            model_name="printmodel",
            name="changeDate",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printmodel",
            name="deliveryDate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printmodel",
            name="documentDate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vote",
            name="MP",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="sejm_app.envoy",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="sejm_app.voting",
            ),
        ),
    ]
