# Generated by Django 5.0 on 2023-12-10 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0010_scandal_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scandal",
            name="author",
            field=models.ForeignKey(
                help_text="Author of the description",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scandals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
