# Generated by Django 5.0 on 2024-01-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0010_alter_stage_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
