# Generated by Django 5.0 on 2024-01-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0011_alter_stage_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="stage_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
