# Generated by Django 5.0 on 2024-03-23 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0011_remove_printmodel_change_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="MP",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="sejm_app.envoy",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="sejm_app.voting",
            ),
        ),
    ]
