# Generated by Django 5.0 on 2023-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0011_alter_scandal_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scandal",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
