# Generated by Django 5.0 on 2024-01-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0012_stage_stage_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
