# Generated by Django 5.0 on 2024-03-24 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0012_alter_vote_mp_alter_vote_voting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interpellation",
            old_name="body_link",
            new_name="bodyLink",
        ),
        migrations.RenameField(
            model_name="interpellation",
            old_name="from_member",
            new_name="fromMember",
        ),
        migrations.RenameField(
            model_name="interpellation",
            old_name="last_modified",
            new_name="lastModified",
        ),
        migrations.RenameField(
            model_name="interpellation",
            old_name="receipt_date",
            new_name="receiptDate",
        ),
        migrations.RenameField(
            model_name="interpellation",
            old_name="repeated_interpellation",
            new_name="repeatedInterpellation",
        ),
        migrations.RenameField(
            model_name="interpellation",
            old_name="sent_date",
            new_name="sentDate",
        ),
    ]
