# Generated by Django 5.0 on 2024-03-24 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0013_rename_body_link_interpellation_bodylink_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply",
            old_name="body_link",
            new_name="bodyLink",
        ),
        migrations.RenameField(
            model_name="reply",
            old_name="from_member",
            new_name="fromMember",
        ),
        migrations.RenameField(
            model_name="reply",
            old_name="from_not_envoy",
            new_name="fromNotEnvoy",
        ),
        migrations.RenameField(
            model_name="reply",
            old_name="last_modified",
            new_name="lastModified",
        ),
        migrations.RenameField(
            model_name="reply",
            old_name="only_attachment",
            new_name="onlyAttachment",
        ),
        migrations.RenameField(
            model_name="reply",
            old_name="receipt_date",
            new_name="receiptDate",
        ),
    ]
