# Generated by Django 5.0 on 2024-01-28 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0013_process_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interpellation",
            fields=[
                (
                    "term",
                    models.IntegerField(help_text="Parliamentary term", null=True),
                ),
                (
                    "num",
                    models.IntegerField(help_text="Interpellation number", null=True),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the interpellation",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "receipt_date",
                    models.DateTimeField(help_text="Date of receipt", null=True),
                ),
                (
                    "last_modified",
                    models.DateTimeField(help_text="Last modified date", null=True),
                ),
                (
                    "body_link",
                    models.URLField(
                        help_text="Link to the interpellation body", null=True
                    ),
                ),
                (
                    "to",
                    models.JSONField(
                        default=list,
                        help_text="Recipients of the interpellation",
                        null=True,
                    ),
                ),
                ("sent_date", models.DateTimeField(help_text="Date sent", null=True)),
                (
                    "repeated_interpellation",
                    models.JSONField(
                        default=list,
                        help_text="Repeated interpellation references",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpellations",
                        to="sejm_app.envoy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("receipt_date", models.DateTimeField()),
                ("last_modified", models.DateTimeField()),
                ("body_link", models.URLField(null=True)),
                ("only_attachment", models.BooleanField(default=False)),
                ("attachments", models.JSONField(default=list)),
                (
                    "from_member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="sejm_app.envoy",
                    ),
                ),
                (
                    "interpolation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="sejm_app.interpellation",
                    ),
                ),
            ],
        ),
    ]
