# Generated by Django 5.0 on 2024-01-28 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0014_interpellation_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reply",
            name="from_member",
        ),
    ]
