# Generated by Django 5.0 on 2024-03-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0015_alter_interpellation_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interpellation",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
