# Generated by Django 5.0 on 2024-01-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0015_remove_reply_from_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="from_member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="sejm_app.envoy",
            ),
        ),
    ]
