# Generated by Django 5.0 on 2024-03-24 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0016_alter_interpellation_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="process",
            old_name="change_date",
            new_name="changeDate",
        ),
        migrations.RenameField(
            model_name="process",
            old_name="created_by",
            new_name="createdBy",
        ),
        migrations.RenameField(
            model_name="process",
            old_name="document_type",
            new_name="documentType",
        ),
        migrations.RenameField(
            model_name="process",
            old_name="legislative_committee",
            new_name="legislativeCommittee",
        ),
        migrations.RenameField(
            model_name="process",
            old_name="principle_of_subsidiarity",
            new_name="principleOfSubsidiarity",
        ),
        migrations.RenameField(
            model_name="process",
            old_name="print_model",
            new_name="printModel",
        ),
        migrations.RenameField(
            model_name="process",
            old_name="process_start_date",
            new_name="processStartDate",
        ),
        migrations.RenameField(
            model_name="process",
            old_name="rcl_num",
            new_name="rclNum",
        ),
        migrations.RenameField(
            model_name="process",
            old_name="urgency_status",
            new_name="urgencyStatus",
        ),
        migrations.RenameField(
            model_name="process",
            old_name="urgency_withdraw_date",
            new_name="urgencyWithdrawDate",
        ),
        migrations.RenameField(
            model_name="stage",
            old_name="sitting_num",
            new_name="sittingNum",
        ),
        migrations.RenameField(
            model_name="stage",
            old_name="stage_name",
            new_name="stageName",
        ),
        migrations.RenameField(
            model_name="stage",
            old_name="stage_number",
            new_name="stageNumber",
        ),
        migrations.RenameField(
            model_name="stage",
            old_name="text_after_3",
            new_name="textAfter3",
        ),
    ]
