# Generated by Django 5.0 on 2024-03-24 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0017_rename_change_date_process_changedate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="documentDate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="process",
            name="term",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="process",
            name="webGeneratedDate",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
