# Generated by Django 5.0 on 2024-03-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0018_process_documentdate_process_term_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voting",
            name="term",
            field=models.IntegerField(
                blank=True, help_text="Sejm term number", null=True
            ),
        ),
    ]
