# Generated by Django 5.0 on 2024-03-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0019_voting_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="comments",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
