# Generated by Django 5.0 on 2024-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0020_process_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="changeDate",
            field=models.DateField(null=True),
        ),
    ]
