# Generated by Django 5.0 on 2024-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0021_alter_process_changedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="webGeneratedDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
