# Generated by Django 5.0 on 2024-03-24 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0022_alter_process_webgenerateddate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nameGenitive", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("appointmentDate", models.DateField()),
                ("compositionDate", models.DateField()),
                ("phone", models.CharField(blank=True, max_length=100)),
                ("scope", models.TextField()),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("function", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="sejm_app.committee",
                    ),
                ),
                (
                    "envoy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sejm_app.envoy"
                    ),
                ),
            ],
            options={
                "unique_together": {("committee", "envoy")},
            },
        ),
    ]
