# Generated by Django 5.0 on 2024-03-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0024_alter_committee_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="name",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="committee",
            name="nameGenitive",
            field=models.CharField(max_length=512),
        ),
    ]
