# Generated by Django 5.0 on 2024-03-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0025_alter_committee_name_alter_committee_namegenitive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="type",
            field=models.CharField(
                choices=[
                    ("EXTRAORDINARY", "Nadzwyczajna"),
                    ("INVESTIGATEŚledcza", "Investigative"),
                    ("STANDINGStała", "Standing"),
                ],
                default="STANDINGStała",
                max_length=50,
            ),
        ),
    ]
