# Generated by Django 5.0 on 2024-03-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0028_alter_committee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="type",
            field=models.CharField(
                choices=[
                    ("EXTRAORDINARY", "Nadzwyczajna"),
                    ("INVESTIGATIVE", "Śledcza"),
                    ("STANDING", "Stała"),
                ],
                default="STANDING",
                max_length=50,
            ),
        ),
    ]
