# Generated by Django 5.0 on 2024-03-14 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles_app", "0002_rename_newsmodel_articlemodel"),
        ("sejm_app", "0006_process_mps_process_club_process_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArticleModel",
            new_name="Article",
        ),
    ]
