# Generated by Django 5.0 on 2023-12-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eli_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Act",
            fields=[
                (
                    "ELI",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("address", models.CharField(max_length=255)),
                ("announcementDate", models.DateField()),
                ("changeDate", models.DateTimeField()),
                ("displayAddress", models.CharField(max_length=255)),
                ("pos", models.IntegerField()),
                ("promulgation", models.DateField()),
                ("textHTML", models.BooleanField()),
                ("textPDF", models.BooleanField()),
                ("title", models.CharField(max_length=255)),
                ("volume", models.IntegerField()),
                ("year", models.IntegerField()),
                ("directives", models.JSONField()),
                ("entryIntoForce", models.DateField()),
                ("inForce", models.CharField(max_length=255)),
                ("keywords", models.ManyToManyField(to="eli_app.keyword")),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eli_app.publisher",
                    ),
                ),
                ("releasedBy", models.ManyToManyField(to="eli_app.institution")),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eli_app.actstatus",
                    ),
                ),
                ("type", models.ManyToManyField(to="eli_app.documenttype")),
            ],
        ),
    ]
