# Generated by Django 5.0 on 2023-12-12 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eli_app", "0004_alter_publisher_actscount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publisher",
            name="years",
        ),
    ]
