# Generated by Django 5.0 on 2023-12-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eli_app", "0005_remove_publisher_years"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="act",
            name="releasedBy",
        ),
        migrations.RemoveField(
            model_name="act",
            name="type",
        ),
        migrations.AddField(
            model_name="act",
            name="releasedBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eli_app.institution",
            ),
        ),
        migrations.AddField(
            model_name="act",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eli_app.documenttype",
            ),
        ),
    ]
