# Generated by Django 5.0 on 2023-12-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eli_app", "0007_alter_act_changedate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="act",
            name="promulgation",
        ),
        migrations.AlterField(
            model_name="act",
            name="changeDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="act",
            name="entryIntoForce",
            field=models.DateField(blank=True, null=True),
        ),
    ]
