# Generated by Django 5.0 on 2023-12-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eli_app", "0008_remove_act_promulgation_alter_act_changedate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="announcementDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
