# Generated by Django 5.0 on 2024-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eli_app", "0009_alter_act_announcementdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="title",
            field=models.CharField(max_length=512),
        ),
    ]
