# Generated by Django 5.0 on 2024-03-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eli_app", "0010_alter_act_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="title",
            field=models.CharField(max_length=1024),
        ),
    ]
