# Generated by Django 4.2.5 on 2023-12-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_vote_vote_delete_votingoption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="listVotes",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="mP",
        ),
        migrations.AlterField(
            model_name="vote",
            name="vote",
            field=models.SmallIntegerField(
                choices=[(1, "Yes"), (0, "No"), (2, "ABSENT")], help_text="Vote option"
            ),
        ),
    ]
