# Generated by Django 4.2.5 on 2023-12-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_voting_abstain_voting_no_voting_yes_alter_vote_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos"),
        ),
    ]
