# Generated by Django 4.2.5 on 2023-12-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_club_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="MP",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="core.envoy",
            ),
        ),
    ]
